### ISSUE TITLE
Crash during date handling

### ISSUE THREAD

**Issue by hulmgulm** [JiCiT/photo_prism_yaml_to_exif#3]
``Today, I ran this script against my photos and it crashes with the following error at one of the photos:

```
Validation failed for type named Hour declared in package DateTime::Types (/usr/local/lib/perl5/site_perl/5.41.3/x86_64-linux-gnu/DateTime/Types.pm) at line 101 in sub named (eval) with value 24

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named Hour declared in package DateTime::Types (/usr/local/lib/perl5/site_perl/5.41.3/x86_64-linux-gnu/DateTime/Types.pm) at line 101 in sub named (eval) with value 24', 'type', 'Specio::Constraint::Simple=HASH(0x55eb17286260)', 'value', 24) called at (eval 241) line 144
DateTime::_check_new_params('day', 01, 'year', 2018, 'time_zone', 'floating', 'hour', 24, 'minute', 24, 'month', 01, 'second', 55) called at /usr/local/lib/perl5/site_perl/5.41.3/x86_64-linux-gnu/DateTime.pm line 177
DateTime::new('DateTime', 'day', 01, 'year', 2018, 'time_zone', 'floating', 'hour', 24, 'minute', 24, 'month', 01, 'second', 55) called at /usr/local/lib/perl5/site_perl/5.41.3/DateTime/Format/Builder/Parser/Regex.pm line 71
DateTime::Format::Builder::Parser::Regex::make('DateTime::Format::Builder::Parser::Regex=HASH(0x55eb17b260c8)', '2018:01:01 24:24:55', undef, 'HASH(0x55eb17b129c0)') called at /usr/local/lib/perl5/site_perl/5.41.3/DateTime/Format/Builder/Parser/generic.pm line 80
DateTime::Format::Builder::Parser::generic::__ANON__('DateTime::Format::EXIF', '2018:01:01 24:24:55', 'HASH(0x55eb1a7fa588)') called at /usr/local/lib/perl5/site_perl/5.41.3/DateTime/Format/Builder/Parser.pm line 268
DateTime::Format::Builder::Parser::__ANON__('DateTime::Format::EXIF', '2018:01:01 24:24:55') called at /usr/local/lib/perl5/site_perl/5.41.3/DateTime/Format/Builder/Parser.pm line 61
DateTime::Format::Builder::Parser::parse('DateTime::Format::Builder::Parser=HASH(0x55eb17893d18)', 'DateTime::Format::EXIF', '2018:01:01 24:24:55') called at /usr/local/lib/perl5/site_perl/5.41.3/DateTime/Format/Builder.pm line 140
DateTime::Format::Builder::__ANON__('DateTime::Format::EXIF', '2018:01:01 24:24:55') called at photo_prism_yaml_to_exif.pl line 305
main::process_file at /usr/local/lib/perl5/5.41.3/File/Find.pm line 455
File::Find::_find_dir('HASH(0x55eb18899858)', '/photos', 29) called at /usr/local/lib/perl5/5.41.3/File/Find.pm line 246
File::Find::_find_opt('HASH(0x55eb18899858)', '/photos') called at /usr/local/lib/perl5/5.41.3/File/Find.pm line 763
File::Find::find('HASH(0x55eb18899858)', '/photos') called at photo_prism_yaml_to_exif.pl line 415
```

The YAML file has the following content:
```
TakenAt: 2018-01-01T00:24:53Z
TakenAtLocal: 2018-01-01T00:24:53Z
TakenSrc: manual
UID: pr1fm2olru9orrn4
Type: image
Title: Portrait / 2018
OriginalName: 2018/0100/20180101002453
TimeZone: Europe/Luxembourg
PlaceSrc: manual
Year: 2018
Month: 1
Day: 1
ISO: 500
Exposure: 1/16
FNumber: 1.7
FocalLength: 4
Quality: 3
Faces: 1
Details:
  Keywords: brown, flash, portrait
  KeywordsSrc: meta
CreatedAt: 2021-10-23T13:13:37Z
UpdatedAt: 2024-01-12T13:13:21Z
EditedAt: 2022-04-06T04:19:59Z
```

Do you have an idea how to fix this?
